### ISSUE TITLE
 I can't install version 0.3.3. Can only install up to 2.0.0

### ISSUE THREAD

**Issue by nop-gkdev** [Radency/flutter_customizable_calendar#42]
Is there a way to fix it?

**Comment by AndriiVivcharenko** [comment]
Hi @nop-gkdev ,

I've fixed a few issues related to the support of Dart `3.0.0` and higher. Currently, the minimum supported version of the Dart SDK is `3.0.0`, which corresponds to Flutter version `3.10.0`. I've already published it on pub.dev. Please try it with version [`0.3.4`](https://github.com/Radency/flutter_customizable_calendar/pull/44) and let me know. 

If you still have issues, please let me know and share the output of `flutter doctor` from your terminal.

**Comment by AndriiVivcharenko** [comment]
Fixed by PR #43
